version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    restart: unless-stopped
    
    volumes:
      - ./:/var/www
    working_dir: /var/www
    environment:
      - APP_ENV=dev
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=app_db
      - DB_USERNAME=app_user
      - DB_PASSWORD=secret
    ports:
      - "5000:5000"
    depends_on:
      - db
      - redis
      - rabbitmq
    command: sh -c "php bin/server.php"

  db:
    image: mysql:8.0
    container_name: db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: app_db
      MYSQL_USER: app_user
      MYSQL_PASSWORD: secret
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  redis:
    image: redis:7
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  db_data:
  redis_data:
  rabbitmq_data:
